'use client';

import React, { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { ArrowLeft, Send, CheckCircle2, Globe, Archive, RefreshCw, Save, Printer } from 'lucide-react';
import { api, Alert, Badge, Button, Card, KeyValue, Skeleton, TextArea, formatDate, formatDateTime } from '@/components/admin/ui';
import { REPORT_STATUS, REPORT_TYPE } from '../ReportList';

type Report = {
    id: string;
    title: string;
    reportType: string;
    status: string;
    periodStart: string;
    periodEnd: string;
    version: number;
    isAutoGenerated: boolean;
    isOutdated: boolean;
    executiveSummary: string | null;
    metricsJson: string | null;
    contentJson: string | null;
    createdAt: string;
    approvedAt: string | null;
    author: { name: string } | null;
    approvedBy: { name: string } | null;
};
type Version = { id: string; version: number; status: string; isOutdated: boolean; createdAt: string };

const LABELS: Record<string, string> = {
    applications: 'Başvurular', total: 'Toplam', byType: 'Türe göre', PROGRAM: 'Program', TEKMER: 'TEKMER', IDEATHON: 'Ideathon', MENTOR: 'Mentör', EVENT: 'Etkinlik', TRAINING: 'Eğitim',
    entrepreneurs: 'Girişimler', new: 'Yeni kayıt', programAssignments: 'Program ataması', spaceAssignments: 'Alan tahsisi',
    operations: 'Operasyon', tasksCreated: 'Oluşturulan görev', tasksCompleted: 'Tamamlanan görev', interactions: 'Görüşme', activities: 'Kurumsal faaliyet',
    programsAndEvents: 'Program & etkinlik', events: 'Etkinlik', trainings: 'Eğitim',
    communication: 'İletişim', newsPublished: 'Yayınlanan haber', formSubmissions: 'Form gönderimi', emailsSent: 'Gönderilen e-posta',
    reservations: 'Rezervasyonlar', CONFIRMED: 'Onaylı', PENDING_APPROVAL: 'Onay bekleyen', CANCELLED: 'İptal', COMPLETED: 'Tamamlandı',
    finance: 'Finans', rentAccrued: 'Kira tahakkuku', rentCollected: 'Kira tahsilatı',
};

function MetricTree({ data, depth = 0 }: { data: unknown; depth?: number }) {
    if (data === null || data === undefined) return <span className="text-gray-500">—</span>;
    if (typeof data !== 'object') return <span className="text-white">{typeof data === 'number' ? data.toLocaleString('tr-TR') : String(data)}</span>;
    if (Array.isArray(data)) return <span className="text-gray-300">{data.length} kayıt</span>;
    const entries = Object.entries(data as Record<string, unknown>);
    if (entries.length === 0) return <span className="text-gray-500">Kayıt yok</span>;
    return (
        <dl className={depth === 0 ? 'grid grid-cols-1 gap-4 md:grid-cols-2' : 'space-y-1'}>
            {entries.map(([k, v]) => (
                <div key={k} className={depth === 0 ? 'rounded-xl border border-white/10 bg-black/20 p-3' : 'flex justify-between gap-3 text-sm'}>
                    <dt className={depth === 0 ? 'mb-2 text-sm font-semibold text-white' : 'text-gray-400'}>{LABELS[k] || k}</dt>
                    <dd className={depth === 0 ? '' : 'text-right'}><MetricTree data={v} depth={depth + 1} /></dd>
                </div>
            ))}
        </dl>
    );
}

export default function ReportDetailPage() {
    const { id } = useParams<{ id: string }>();
    const [report, setReport] = useState<Report | null>(null);
    const [versions, setVersions] = useState<Version[]>([]);
    const [summary, setSummary] = useState('');
    const [error, setError] = useState<string | null>(null);
    const [notice, setNotice] = useState<string | null>(null);
    const [busy, setBusy] = useState<string | null>(null);

    const load = useCallback(async () => {
        try {
            const d = await api<{ report: Report; versions: Version[] }>(`/api/admin/reports/${id}`);
            setReport(d.report);
            setVersions(d.versions);
            setSummary(d.report.executiveSummary || '');
        } catch (e) {
            setError(e instanceof Error ? e.message : 'Rapor alınamadı');
        }
    }, [id]);

    useEffect(() => {
        const t = setTimeout(load, 0);
        return () => clearTimeout(t);
    }, [load]);

    const act = async (action: string, extra: Record<string, unknown> = {}) => {
        setBusy(action);
        setError(null);
        try {
            const d = await api<{ report: Report }>(`/api/admin/reports/${id}`, { method: 'PUT', json: { action, ...extra } });
            if (action === 'REGENERATE') {
                window.location.href = `/admin/raporlar/${d.report.id}`;
                return;
            }
            setNotice('İşlem tamamlandı.');
            load();
        } catch (e) {
            setError(e instanceof Error ? e.message : 'İşlem başarısız');
        } finally {
            setBusy(null);
        }
    };

    if (error && !report) return <div className="space-y-4"><Link href="/admin/raporlar" className="text-sm text-gray-400 hover:text-white">← Raporlar</Link><Alert tone="danger">{error}</Alert></div>;
    if (!report) return <Skeleton rows={6} />;

    let metrics: unknown = null;
    try {
        metrics = report.metricsJson ? JSON.parse(report.metricsJson) : null;
    } catch {
        metrics = null;
    }
    const editable = !['APPROVED', 'PUBLISHED', 'ARCHIVED'].includes(report.status);

    return (
        <div className="space-y-5 pb-12">
            <div className="flex flex-wrap items-start justify-between gap-3">
                <div>
                    <Link href="/admin/raporlar" className="mb-2 inline-flex items-center gap-1 text-xs text-gray-400 hover:text-white"><ArrowLeft className="h-3.5 w-3.5" /> Raporlar</Link>
                    <h1 className="text-xl font-bold text-white">{report.title}</h1>
                    <div className="mt-1 flex flex-wrap items-center gap-1.5">
                        <Badge tone="info">{REPORT_TYPE[report.reportType] || report.reportType}</Badge>
                        <Badge tone={REPORT_STATUS[report.status]?.tone || 'neutral'}>{REPORT_STATUS[report.status]?.label || report.status}</Badge>
                        {report.isAutoGenerated && <Badge>Otomatik · v{report.version}</Badge>}
                    </div>
                </div>
                <div className="flex flex-wrap gap-2 print:hidden">
                    <Button icon={Printer} onClick={() => window.print()}>Yazdır / PDF</Button>
                    {report.isAutoGenerated && <Button icon={RefreshCw} loading={busy === 'REGENERATE'} onClick={() => act('REGENERATE')}>Yeni sürüm oluştur</Button>}
                    {['DRAFT', 'AUTO_GENERATED_DRAFT'].includes(report.status) && <Button icon={Send} loading={busy === 'SUBMIT'} onClick={() => act('SUBMIT')}>Onaya gönder</Button>}
                    {['IN_REVIEW', 'DRAFT', 'AUTO_GENERATED_DRAFT'].includes(report.status) && <Button variant="primary" icon={CheckCircle2} loading={busy === 'APPROVE'} onClick={() => act('APPROVE')}>Onayla</Button>}
                    {report.status === 'APPROVED' && <Button variant="primary" icon={Globe} loading={busy === 'PUBLISH'} onClick={() => act('PUBLISH')}>Yayınla</Button>}
                    {report.status !== 'ARCHIVED' && <Button variant="ghost" icon={Archive} loading={busy === 'ARCHIVE'} onClick={() => act('ARCHIVE')}>Arşivle</Button>}
                </div>
            </div>

            {report.isOutdated && <Alert tone="warning" title="Rapor verileri değişti">Bu rapor oluşturulduktan sonra ilgili dönemin kayıtları değişti. Onaylamadan önce yeni sürüm oluşturun; mevcut sürüm geçmiş olarak saklanır.</Alert>}
            {error && <Alert tone="danger" onClose={() => setError(null)}>{error}</Alert>}
            {notice && <Alert tone="success" onClose={() => setNotice(null)}>{notice}</Alert>}

            <Card>
                <KeyValue items={[
                    { label: 'Dönem', value: `${formatDate(report.periodStart)} – ${formatDate(report.periodEnd)}` },
                    { label: 'Hazırlayan', value: report.author?.name || 'Sistem (otomatik)' },
                    { label: 'Oluşturma', value: formatDateTime(report.createdAt) },
                    { label: 'Onay', value: report.approvedAt ? `${report.approvedBy?.name || '—'} · ${formatDateTime(report.approvedAt)}` : '—' },
                ]} />
            </Card>

            <Card>
                <div className="mb-2 text-sm font-semibold text-white">Yönetici özeti</div>
                {editable ? (
                    <>
                        <TextArea rows={6} value={summary} onChange={(e) => setSummary(e.target.value)} />
                        <div className="mt-2 flex justify-end print:hidden">
                            <Button icon={Save} loading={busy === 'UPDATE_SUMMARY'} disabled={summary === (report.executiveSummary || '')} onClick={() => act('UPDATE_SUMMARY', { executiveSummary: summary })}>Özeti kaydet</Button>
                        </div>
                    </>
                ) : (
                    <p className="whitespace-pre-wrap text-sm text-gray-200">{report.executiveSummary || '—'}</p>
                )}
            </Card>

            {metrics !== null && (
                <Card>
                    <div className="mb-3 text-sm font-semibold text-white">Veriler</div>
                    <MetricTree data={metrics} />
                </Card>
            )}

            {versions.length > 1 && (
                <Card>
                    <div className="mb-2 text-sm font-semibold text-white">Sürümler</div>
                    <ul className="space-y-1 text-sm">
                        {versions.map((v) => (
                            <li key={v.id} className="flex items-center justify-between">
                                <Link href={`/admin/raporlar/${v.id}`} className={v.id === report.id ? 'font-semibold text-white' : 'text-blue-300 hover:underline'}>v{v.version} · {REPORT_STATUS[v.status]?.label || v.status}</Link>
                                <span className="text-xs text-gray-500">{v.isOutdated ? 'Güncel değil · ' : ''}{formatDateTime(v.createdAt)}</span>
                            </li>
                        ))}
                    </ul>
                </Card>
            )}
        </div>
    );
}
