/**
 * Automatic reports: Europe/Istanbul period boundaries, idempotent generation,
 * outdated detection and versioning. Reports created here are removed by exact id.
 */
import { test, describe, after } from 'node:test';
import assert from 'node:assert';
import { prisma } from '../lib/prisma';
import { periodsToCover, ReportAutomationService } from '../lib/services/report-automation-service';

const createdIds: string[] = [];
const createdEntrepreneurs: string[] = [];

describe('Report automation', () => {
    after(async () => {
        await prisma.auditLog.deleteMany({ where: { entityType: 'OperationalReport', entityId: { in: createdIds } } });
        await prisma.operationalReport.deleteMany({ where: { id: { in: createdIds } } });
        await prisma.entrepreneur.deleteMany({ where: { id: { in: createdEntrepreneurs } } });
        await prisma.$disconnect();
    });

    test('periods follow Istanbul calendar and exclude the current period', () => {
        // 2026-03-01 00:30 in Istanbul is still 28 Feb in UTC
        const now = new Date('2026-02-28T21:30:00Z');
        const daily = periodsToCover('DAILY', now);
        assert.equal(daily[0].key, 'DAILY:2026-02-28');
        assert.equal(daily[0].start.toISOString(), '2026-02-27T21:00:00.000Z');
        const monthly = periodsToCover('MONTHLY', now);
        assert.equal(monthly[0].key, 'MONTHLY:2026-02');
        assert.equal(monthly[0].end.toISOString(), '2026-02-28T21:00:00.000Z');
        assert.equal(periodsToCover('MONTHLY', new Date('2026-01-15T10:00:00Z'))[0].key, 'MONTHLY:2025-12');
        assert.equal(periodsToCover('YEARLY', now)[0].key, 'YEARLY:2025');
    });

    test('generation is idempotent, flags changed data and versions on regenerate', async () => {
        // Use a far-past "now" so the periods do not collide with real local reports
        const now = new Date('2001-06-15T09:00:00Z');
        const first = await ReportAutomationService.runScheduled(now, ['MONTHLY']);
        const reports = await prisma.operationalReport.findMany({ where: { periodKey: { in: first.created }, isAutoGenerated: true } });
        createdIds.push(...reports.map((r) => r.id));
        assert.equal(first.created.length, 3, 'three missed months recovered');
        assert.ok(reports.every((r) => r.status === 'AUTO_GENERATED_DRAFT' && r.authorId === null));

        const second = await ReportAutomationService.runScheduled(now, ['MONTHLY']);
        assert.equal(second.created.length, 0, 'second run creates nothing');

        // Back-dated record in May 2001 changes that month's figures
        const e = await prisma.entrepreneur.create({ data: { name: 'qa-ra Backdated', slug: `qa-ra-${Date.now()}`, sector: 'QA', createdAt: new Date('2001-05-10T10:00:00Z') } });
        createdEntrepreneurs.push(e.id);
        const third = await ReportAutomationService.runScheduled(now, ['MONTHLY']);
        assert.deepEqual(third.outdated, ['MONTHLY:2001-05']);

        const may = reports.find((r) => r.periodKey === 'MONTHLY:2001-05');
        assert.ok(may);
        const actor = await prisma.user.findFirst({ select: { id: true, name: true, email: true } });
        assert.ok(actor);
        const v2 = await ReportAutomationService.regenerate(may.id, actor);
        createdIds.push(v2.id);
        assert.equal(v2.version, 2);
        assert.equal(v2.supersedesId, may.id);
        assert.equal(JSON.parse(v2.metricsJson || '{}').entrepreneurs.new, 1);
        await assert.rejects(() => ReportAutomationService.regenerate(may.id, actor), /daha yeni/);
    });
});
