'use client';

import React, { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { FileText, RefreshCw, Bot } from 'lucide-react';
import { api, Badge, Button, Card, EmptyState, Skeleton, Tabs, Alert, formatDate } from '@/components/admin/ui';

export type ReportRow = {
    id: string;
    title: string;
    reportType: string;
    status: string;
    periodStart: string;
    periodEnd: string;
    version: number;
    isAutoGenerated: boolean;
    isOutdated: boolean;
    createdAt: string;
    author: { name: string } | null;
};

export const REPORT_STATUS: Record<string, { label: string; tone: 'neutral' | 'info' | 'success' | 'warning' | 'primary' }> = {
    AUTO_GENERATED_DRAFT: { label: 'Otomatik taslak', tone: 'info' },
    DRAFT: { label: 'Taslak', tone: 'neutral' },
    IN_REVIEW: { label: 'Onay bekliyor', tone: 'warning' },
    APPROVED: { label: 'Onaylandı', tone: 'success' },
    PUBLISHED: { label: 'Yayınlandı', tone: 'primary' },
    ARCHIVED: { label: 'Arşiv', tone: 'neutral' },
};
export const REPORT_TYPE: Record<string, string> = { DAILY: 'Günlük', MONTHLY: 'Aylık', YEARLY: 'Yıllık', TEAM: 'Ekip', SOCIAL: 'Sosyal medya', CROSS_CHANNEL: 'Çok kanallı', CUSTOM: 'Özel' };

type View = 'all' | 'auto' | 'review' | 'published';

export function ReportList() {
    const [reports, setReports] = useState<ReportRow[] | null>(null);
    const [view, setView] = useState<View>('all');
    const [running, setRunning] = useState(false);
    const [notice, setNotice] = useState<{ tone: 'success' | 'danger' | 'info'; text: string } | null>(null);

    const load = useCallback(async () => {
        try {
            const d = await api<{ reports: ReportRow[] }>('/api/admin/reports');
            setReports(d.reports);
        } catch (e) {
            setNotice({ tone: 'danger', text: e instanceof Error ? e.message : 'Raporlar alınamadı' });
            setReports([]);
        }
    }, []);

    useEffect(() => {
        const t = setTimeout(load, 0);
        return () => clearTimeout(t);
    }, [load]);

    const runAutomation = async () => {
        setRunning(true);
        try {
            const d = await api<{ result: { created: string[]; outdated: string[]; unchanged: number } }>('/api/admin/reports', { method: 'POST', json: { action: 'runAutomation' } });
            const r = d.result;
            setNotice({ tone: 'success', text: `Otomatik raporlar kontrol edildi: ${r.created.length} yeni, ${r.outdated.length} güncel olmayan, ${r.unchanged} değişmemiş.` });
            load();
        } catch (e) {
            setNotice({ tone: 'danger', text: e instanceof Error ? e.message : 'Otomatik raporlar çalıştırılamadı' });
        } finally {
            setRunning(false);
        }
    };

    const filtered = (reports || []).filter((r) => (view === 'auto' ? r.isAutoGenerated : view === 'review' ? r.status === 'IN_REVIEW' : view === 'published' ? r.status === 'PUBLISHED' : true));

    return (
        <Card>
            <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
                <h2 className="flex items-center gap-2 text-lg font-bold text-white"><FileText className="h-5 w-5 text-cyan-400" /> Raporlar</h2>
                <Button icon={RefreshCw} loading={running} onClick={runAutomation}>Otomatik raporları kontrol et</Button>
            </div>
            {notice && <div className="mb-3"><Alert tone={notice.tone} onClose={() => setNotice(null)}>{notice.text}</Alert></div>}
            <Tabs
                value={view}
                onChange={setView}
                tabs={[
                    { value: 'all', label: 'Tümü', count: reports?.length ?? null },
                    { value: 'auto', label: 'Otomatik', icon: Bot, count: reports?.filter((r) => r.isAutoGenerated).length ?? null },
                    { value: 'review', label: 'Onay bekleyen', count: reports?.filter((r) => r.status === 'IN_REVIEW').length ?? null },
                    { value: 'published', label: 'Yayınlanan', count: reports?.filter((r) => r.status === 'PUBLISHED').length ?? null },
                ]}
            />
            <div className="mt-4 space-y-2">
                {!reports ? <Skeleton /> : filtered.length === 0 ? (
                    <EmptyState icon={FileText} title="Rapor yok" description={view === 'auto' ? 'Otomatik raporlar zamanlayıcı çalıştığında veya "Otomatik raporları kontrol et" ile oluşturulur.' : 'Bu görünümde rapor bulunmuyor.'} />
                ) : (
                    filtered.map((r) => (
                        <Link key={r.id} href={`/admin/raporlar/${r.id}`} className="flex flex-col justify-between gap-2 rounded-xl border border-white/10 bg-black/20 p-3 hover:border-white/25 sm:flex-row sm:items-center">
                            <div className="min-w-0">
                                <div className="mb-1 flex flex-wrap items-center gap-1.5">
                                    <Badge tone="info">{REPORT_TYPE[r.reportType] || r.reportType}</Badge>
                                    <Badge tone={REPORT_STATUS[r.status]?.tone || 'neutral'}>{REPORT_STATUS[r.status]?.label || r.status}</Badge>
                                    {r.isAutoGenerated && <Badge>v{r.version}</Badge>}
                                    {r.isOutdated && <Badge tone="warning">Veriler değişti</Badge>}
                                </div>
                                <div className="truncate text-sm font-semibold text-white">{r.title}</div>
                                <div className="text-xs text-gray-400">{formatDate(r.periodStart)} – {formatDate(r.periodEnd)} · {r.author?.name || 'Sistem (otomatik)'}</div>
                            </div>
                            <span className="shrink-0 text-xs text-gray-400">İncele →</span>
                        </Link>
                    ))
                )}
            </div>
        </Card>
    );
}
