import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { hasPermission } from '@/lib/rbac';
import { logAuditEvent } from '@/lib/audit';
import { requireAdmin, errorResponse, DomainError } from '@/lib/api-guard';
import { ReportingService } from '@/lib/services/reporting-service';
import { ReportAutomationService } from '@/lib/services/report-automation-service';

type Params = { params: Promise<{ id: string }> };

async function loadVisible(id: string, user: Parameters<typeof hasPermission>[0] & { id: string }) {
    const report = await ReportingService.getReportById(id);
    if (!report) throw new DomainError('Rapor bulunamadı', 404);
    const visible = hasPermission(user, 'approve', 'reports') || report.authorId === user.id || report.isAutoGenerated || report.status === 'PUBLISHED';
    if (!visible) throw new DomainError('Bu raporu görüntüleme yetkiniz yok', 403);
    return report;
}

export async function GET(request: NextRequest, { params }: Params) {
    const auth = await requireAdmin(request, 'view', 'reports');
    if (auth.error) return auth.error;
    try {
        const { id } = await params;
        const report = await loadVisible(id, auth.user);
        const versions = report.periodKey
            ? await prisma.operationalReport.findMany({ where: { periodKey: report.periodKey, isAutoGenerated: report.isAutoGenerated }, select: { id: true, version: true, status: true, isOutdated: true, createdAt: true }, orderBy: { version: 'desc' } })
            : [];
        return NextResponse.json({ success: true, report, versions });
    } catch (error) {
        return errorResponse(error, 'Rapor alınamadı');
    }
}

/** Workflow: SUBMIT (author) → APPROVE (reports:approve) → PUBLISH (reports:publish); ARCHIVE; REGENERATE (automatic reports). */
export async function PUT(request: NextRequest, { params }: Params) {
    const auth = await requireAdmin(request, 'view', 'reports');
    if (auth.error) return auth.error;
    try {
        const { id } = await params;
        const body = (await request.json()) as { action?: string; executiveSummary?: string };
        const report = await loadVisible(id, auth.user);
        const can = (a: string) => hasPermission(auth.user, a, 'reports');
        const log = (action: string, diff: string) => logAuditEvent({ actorId: auth.actor.id, actorEmail: auth.actor.email, actorName: auth.actor.name, action, entityType: 'OperationalReport', entityId: id, diff });

        switch (body.action) {
            case 'UPDATE_SUMMARY': {
                if (!can('create') || (report.authorId && report.authorId !== auth.user.id && !can('approve'))) throw new DomainError('Bu raporu düzenleme yetkiniz yok', 403);
                if (['APPROVED', 'PUBLISHED', 'ARCHIVED'].includes(report.status)) throw new DomainError('Onaylanmış veya yayınlanmış rapor düzenlenemez', 409);
                const updated = await prisma.operationalReport.update({ where: { id }, data: { executiveSummary: String(body.executiveSummary || ''), status: report.status === 'AUTO_GENERATED_DRAFT' ? 'DRAFT' : report.status } });
                await log('UPDATE', 'Rapor özeti düzenlendi');
                return NextResponse.json({ success: true, report: updated });
            }
            case 'SUBMIT': {
                if (!can('create')) throw new DomainError('Yetkiniz yok', 403);
                if (!['DRAFT', 'AUTO_GENERATED_DRAFT'].includes(report.status)) throw new DomainError('Yalnızca taslak raporlar onaya gönderilebilir', 409);
                const updated = await prisma.operationalReport.update({ where: { id }, data: { status: 'IN_REVIEW' } });
                await log('SUBMIT', 'Rapor onaya gönderildi');
                return NextResponse.json({ success: true, report: updated });
            }
            case 'APPROVE': {
                if (!can('approve')) throw new DomainError('Rapor onaylama yetkiniz yok', 403);
                if (report.isOutdated) throw new DomainError('Rapor verileri değişmiş; önce yeni sürüm oluşturun', 409);
                const updated = await ReportingService.approveReport(id, auth.user.id, auth.actor);
                return NextResponse.json({ success: true, report: updated });
            }
            case 'PUBLISH': {
                if (!can('publish')) throw new DomainError('Rapor yayınlama yetkiniz yok', 403);
                if (report.status !== 'APPROVED') throw new DomainError('Yalnızca onaylanmış raporlar yayınlanabilir', 409);
                const updated = await prisma.operationalReport.update({ where: { id }, data: { status: 'PUBLISHED' } });
                await log('PUBLISH', 'Rapor yayınlandı');
                return NextResponse.json({ success: true, report: updated });
            }
            case 'ARCHIVE': {
                if (!can('approve') && report.authorId !== auth.user.id) throw new DomainError('Yetkiniz yok', 403);
                const updated = await prisma.operationalReport.update({ where: { id }, data: { status: 'ARCHIVED' } });
                await log('ARCHIVE', 'Rapor arşivlendi');
                return NextResponse.json({ success: true, report: updated });
            }
            case 'REGENERATE': {
                if (!can('create')) throw new DomainError('Yetkiniz yok', 403);
                const created = await ReportAutomationService.regenerate(id, auth.actor);
                return NextResponse.json({ success: true, report: created });
            }
            default:
                throw new DomainError('Geçersiz işlem');
        }
    } catch (error) {
        return errorResponse(error, 'Rapor işlemi başarısız');
    }
}
