import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { prisma } from '@/lib/prisma';
import { hasPermission } from '@/lib/rbac';
import { requireAdmin, errorResponse } from '@/lib/api-guard';
import { ReportingService } from '@/lib/services/reporting-service';
import { ReportAutomationService } from '@/lib/services/report-automation-service';

const reportSaveSchema = z.object({
    title: z.string().min(1, 'Rapor başlığı zorunludur'),
    reportType: z.enum(['DAILY', 'MONTHLY', 'TEAM', 'YEARLY', 'SOCIAL', 'CROSS_CHANNEL', 'CUSTOM']),
    periodStart: z.string().min(1),
    periodEnd: z.string().min(1),
    executiveSummary: z.string().optional(),
    contentJson: z.unknown().optional(),
    metricsJson: z.unknown().optional(),
    department: z.string().optional(),
    status: z.enum(['DRAFT', 'IN_REVIEW']).optional(),
});

/**
 * Report list. Approvers see every report; other users see their own reports,
 * automatic institutional reports and published reports.
 */
export async function GET(request: NextRequest) {
    const auth = await requireAdmin(request, 'view', 'reports');
    if (auth.error) return auth.error;
    try {
        const sp = new URL(request.url).searchParams;
        const where: Record<string, unknown> = {};
        if (sp.get('reportType')) where.reportType = sp.get('reportType');
        if (sp.get('status')) where.status = sp.get('status');
        if (sp.get('auto') === 'true') where.isAutoGenerated = true;
        if (!hasPermission(auth.user, 'approve', 'reports')) {
            where.OR = [{ authorId: auth.user.id }, { isAutoGenerated: true }, { status: 'PUBLISHED' }];
        }
        const reports = await prisma.operationalReport.findMany({
            where,
            include: { author: { select: { id: true, name: true, email: true, department: true } }, approvedBy: { select: { id: true, name: true } } },
            orderBy: [{ periodStart: 'desc' }, { version: 'desc' }],
            take: 300,
        });
        return NextResponse.json({ success: true, reports });
    } catch (error) {
        return errorResponse(error, 'Raporlar alınamadı');
    }
}

export async function POST(request: NextRequest) {
    const auth = await requireAdmin(request, 'create', 'reports');
    if (auth.error) return auth.error;
    try {
        const body = (await request.json()) as Record<string, unknown>;
        if (body.action === 'runAutomation') {
            const result = await ReportAutomationService.runScheduled();
            return NextResponse.json({ success: true, result });
        }
        const parsed = reportSaveSchema.safeParse(body);
        if (!parsed.success) return NextResponse.json({ success: false, message: parsed.error.issues[0]?.message || 'Geçersiz veri' }, { status: 400 });
        const report = await ReportingService.saveReport(parsed.data, auth.user.id, auth.actor);
        return NextResponse.json({ success: true, report });
    } catch (error) {
        return errorResponse(error, 'Rapor kaydedilemedi');
    }
}
