-- Admin platform completion: Form Center, campaigns, reservations, space assignments,
-- 3D experiences, documents, notification reads, email scheduling, automatic reports.
-- Non-destructive: adds tables/columns, relaxes NOT NULL, changes FK delete rules
-- (financial records RESTRICT instead of CASCADE). Apply with: prisma migrate deploy

-- DropForeignKey
ALTER TABLE "EntrepreneurProgram" DROP CONSTRAINT "EntrepreneurProgram_entrepreneurId_fkey";

-- DropForeignKey
ALTER TABLE "EntrepreneurProgram" DROP CONSTRAINT "EntrepreneurProgram_programId_fkey";

-- DropForeignKey
ALTER TABLE "FundingReceipt" DROP CONSTRAINT "FundingReceipt_fundingSourceId_fkey";

-- DropForeignKey
ALTER TABLE "FundingSource" DROP CONSTRAINT "FundingSource_projectId_fkey";

-- DropForeignKey
ALTER TABLE "OperationalReport" DROP CONSTRAINT "OperationalReport_authorId_fkey";

-- DropForeignKey
ALTER TABLE "ProjectExpense" DROP CONSTRAINT "ProjectExpense_projectId_fkey";

-- DropForeignKey
ALTER TABLE "RentAccrual" DROP CONSTRAINT "RentAccrual_contractId_fkey";

-- DropForeignKey
ALTER TABLE "RentAccrual" DROP CONSTRAINT "RentAccrual_entrepreneurId_fkey";

-- DropForeignKey
ALTER TABLE "RentContract" DROP CONSTRAINT "RentContract_entrepreneurId_fkey";

-- DropForeignKey
ALTER TABLE "RentPayment" DROP CONSTRAINT "RentPayment_accrualId_fkey";

-- DropForeignKey
ALTER TABLE "RentPayment" DROP CONSTRAINT "RentPayment_entrepreneurId_fkey";

-- DropForeignKey
ALTER TABLE "Reservation" DROP CONSTRAINT "Reservation_userId_fkey";

-- AlterTable
ALTER TABLE "Application" ADD COLUMN     "applicantType" TEXT NOT NULL DEFAULT 'PERSON',
ADD COLUMN     "applicationType" TEXT NOT NULL DEFAULT 'PROGRAM',
ADD COLUMN     "campaignId" TEXT,
ADD COLUMN     "decidedAt" TIMESTAMP(3),
ADD COLUMN     "decidedById" TEXT,
ADD COLUMN     "decisionNote" TEXT,
ADD COLUMN     "entrepreneurId" TEXT,
ADD COLUMN     "organizationId" TEXT,
ADD COLUMN     "personId" TEXT;

-- AlterTable
ALTER TABLE "EmailOutbox" ADD COLUMN     "ccEmails" TEXT,
ADD COLUMN     "createdById" TEXT,
ADD COLUMN     "scheduledAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Form" ADD COLUMN     "archivedAt" TIMESTAMP(3),
ADD COLUMN     "confirmationTemplateKey" TEXT,
ADD COLUMN     "isTemplate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "notifyEmails" TEXT,
ADD COLUMN     "ownerId" TEXT,
ADD COLUMN     "publicPath" TEXT,
ADD COLUMN     "sourceFormId" TEXT,
ADD COLUMN     "submitLabel" TEXT,
ADD COLUMN     "theme" TEXT;

-- AlterTable
ALTER TABLE "FormField" ADD COLUMN     "sectionDescription" TEXT,
ADD COLUMN     "uiConfig" TEXT;

-- AlterTable
ALTER TABLE "FormVersion" ADD COLUMN     "changeNote" TEXT,
ADD COLUMN     "createdById" TEXT;

-- AlterTable
ALTER TABLE "KvkkConsent" ADD COLUMN     "personId" TEXT;

-- AlterTable
ALTER TABLE "OperationalReport" ADD COLUMN     "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isOutdated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "periodKey" TEXT,
ADD COLUMN     "supersedesId" TEXT,
ALTER COLUMN "authorId" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Person" ADD COLUMN     "address" TEXT,
ADD COLUMN     "birthDate" TIMESTAMP(3),
ADD COLUMN     "businessRoles" TEXT,
ADD COLUMN     "dataSource" TEXT DEFAULT 'MANUAL_ADMIN',
ADD COLUMN     "extension" TEXT,
ADD COLUMN     "isTurkishCitizen" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "nationality" TEXT DEFAULT 'TC',
ADD COLUMN     "personalEmail" TEXT,
ADD COLUMN     "postalCode" TEXT,
ADD COLUMN     "primaryEmailType" TEXT DEFAULT 'WORK',
ADD COLUMN     "privacyConsents" TEXT,
ADD COLUMN     "salutation" TEXT,
ADD COLUMN     "state" TEXT,
ADD COLUMN     "tcNumberEncrypted" TEXT,
ADD COLUMN     "tcNumberHash" TEXT,
ADD COLUMN     "tcNumberMasked" TEXT,
ADD COLUMN     "websiteUrl" TEXT,
ADD COLUMN     "workEmail" TEXT,
ADD COLUMN     "workPhone" TEXT;

-- AlterTable
ALTER TABLE "Reservation" ADD COLUMN     "alternativeJson" TEXT,
ADD COLUMN     "decidedAt" TIMESTAMP(3),
ADD COLUMN     "decidedById" TEXT,
ADD COLUMN     "decisionNote" TEXT,
ADD COLUMN     "organizationId" TEXT,
ADD COLUMN     "personId" TEXT,
ADD COLUMN     "purpose" TEXT,
ADD COLUMN     "requesterEmail" TEXT,
ADD COLUMN     "requesterName" TEXT,
ADD COLUMN     "requesterOrganization" TEXT,
ADD COLUMN     "requesterPhone" TEXT,
ADD COLUMN     "source" TEXT NOT NULL DEFAULT 'ADMIN',
ADD COLUMN     "submissionId" TEXT,
ALTER COLUMN "userId" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Resource" ALTER COLUMN "capacity" DROP NOT NULL,
ALTER COLUMN "capacity" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Submission" ADD COLUMN     "applicantEmail" TEXT,
ADD COLUMN     "applicantName" TEXT,
ADD COLUMN     "campaignId" TEXT,
ADD COLUMN     "consentSnapshot" TEXT,
ADD COLUMN     "contextJson" TEXT,
ADD COLUMN     "formId" TEXT,
ADD COLUMN     "organizationId" TEXT,
ADD COLUMN     "personId" TEXT,
ADD COLUMN     "privacyTextIds" TEXT;

-- AlterTable
ALTER TABLE "Task" ADD COLUMN     "organizationId" TEXT,
ADD COLUMN     "personId" TEXT,
ADD COLUMN     "projectId" TEXT,
ADD COLUMN     "rentContractId" TEXT,
ADD COLUMN     "reservationId" TEXT;

-- CreateTable
CREATE TABLE "ApplicationCampaign" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "applicationType" TEXT NOT NULL,
    "description" TEXT,
    "status" TEXT NOT NULL DEFAULT 'DRAFT',
    "programId" TEXT,
    "formId" TEXT,
    "evaluationTemplateId" TEXT,
    "ownerId" TEXT,
    "opensAt" TIMESTAMP(3),
    "closesAt" TIMESTAMP(3),
    "publicPath" TEXT,
    "allowedApplicantTypes" TEXT,
    "workflowStages" TEXT,
    "requiredDocuments" TEXT,
    "notificationRecipients" TEXT,
    "confirmationTemplateKey" TEXT,
    "statusTemplateMap" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ApplicationCampaign_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SpaceAssignment" (
    "id" TEXT NOT NULL,
    "facilityId" TEXT NOT NULL,
    "entrepreneurId" TEXT,
    "organizationId" TEXT,
    "applicationId" TEXT,
    "rentContractId" TEXT,
    "status" TEXT NOT NULL DEFAULT 'PLANNED',
    "unitLabel" TEXT,
    "startDate" TIMESTAMP(3),
    "endDate" TIMESTAMP(3),
    "notes" TEXT,
    "createdById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SpaceAssignment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FacilityExperience" (
    "id" TEXT NOT NULL,
    "facilityId" TEXT NOT NULL,
    "isEnabled" BOOLEAN NOT NULL DEFAULT false,
    "isPublic" BOOLEAN NOT NULL DEFAULT false,
    "mode" TEXT NOT NULL DEFAULT 'MODEL',
    "modelUrl" TEXT,
    "modelMediaId" TEXT,
    "panoramaUrl" TEXT,
    "panoramaMediaId" TEXT,
    "posterUrl" TEXT,
    "posterMediaId" TEXT,
    "altText" TEXT,
    "description" TEXT,
    "cameraOrbit" TEXT,
    "cameraTarget" TEXT,
    "autoRotate" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FacilityExperience_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FacilityHotspot" (
    "id" TEXT NOT NULL,
    "experienceId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "hotspotType" TEXT NOT NULL DEFAULT 'INFO',
    "position" TEXT NOT NULL,
    "normal" TEXT,
    "linkUrl" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FacilityHotspot_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Document" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "category" TEXT NOT NULL DEFAULT 'GENERAL',
    "mediaId" TEXT NOT NULL,
    "entityType" TEXT NOT NULL,
    "entityId" TEXT NOT NULL,
    "visibility" TEXT NOT NULL DEFAULT 'INTERNAL',
    "isArchived" BOOLEAN NOT NULL DEFAULT false,
    "uploadedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Document_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "NotificationRead" (
    "id" TEXT NOT NULL,
    "notificationId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "readAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "NotificationRead_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ApplicationCampaign_slug_key" ON "ApplicationCampaign"("slug");

-- CreateIndex
CREATE INDEX "ApplicationCampaign_applicationType_idx" ON "ApplicationCampaign"("applicationType");

-- CreateIndex
CREATE INDEX "ApplicationCampaign_status_idx" ON "ApplicationCampaign"("status");

-- CreateIndex
CREATE INDEX "ApplicationCampaign_programId_idx" ON "ApplicationCampaign"("programId");

-- CreateIndex
CREATE INDEX "SpaceAssignment_facilityId_idx" ON "SpaceAssignment"("facilityId");

-- CreateIndex
CREATE INDEX "SpaceAssignment_entrepreneurId_idx" ON "SpaceAssignment"("entrepreneurId");

-- CreateIndex
CREATE INDEX "SpaceAssignment_organizationId_idx" ON "SpaceAssignment"("organizationId");

-- CreateIndex
CREATE INDEX "SpaceAssignment_status_idx" ON "SpaceAssignment"("status");

-- CreateIndex
CREATE UNIQUE INDEX "FacilityExperience_facilityId_key" ON "FacilityExperience"("facilityId");

-- CreateIndex
CREATE INDEX "FacilityHotspot_experienceId_idx" ON "FacilityHotspot"("experienceId");

-- CreateIndex
CREATE INDEX "Document_entityType_entityId_idx" ON "Document"("entityType", "entityId");

-- CreateIndex
CREATE INDEX "Document_category_idx" ON "Document"("category");

-- CreateIndex
CREATE INDEX "NotificationRead_userId_idx" ON "NotificationRead"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "NotificationRead_notificationId_userId_key" ON "NotificationRead"("notificationId", "userId");

-- CreateIndex
CREATE INDEX "Application_applicationType_idx" ON "Application"("applicationType");

-- CreateIndex
CREATE INDEX "Application_campaignId_idx" ON "Application"("campaignId");

-- CreateIndex
CREATE INDEX "EmailOutbox_scheduledAt_idx" ON "EmailOutbox"("scheduledAt");

-- CreateIndex
CREATE INDEX "OperationalReport_reportType_periodKey_idx" ON "OperationalReport"("reportType", "periodKey");

-- CreateIndex
CREATE INDEX "Person_tcNumberHash_idx" ON "Person"("tcNumberHash");

-- CreateIndex
CREATE INDEX "Submission_formId_idx" ON "Submission"("formId");

-- CreateIndex
CREATE INDEX "Submission_campaignId_idx" ON "Submission"("campaignId");

-- AddForeignKey
ALTER TABLE "Task" ADD CONSTRAINT "Task_personId_fkey" FOREIGN KEY ("personId") REFERENCES "Person"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Task" ADD CONSTRAINT "Task_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Task" ADD CONSTRAINT "Task_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Task" ADD CONSTRAINT "Task_reservationId_fkey" FOREIGN KEY ("reservationId") REFERENCES "Reservation"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Task" ADD CONSTRAINT "Task_rentContractId_fkey" FOREIGN KEY ("rentContractId") REFERENCES "RentContract"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Form" ADD CONSTRAINT "Form_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Submission" ADD CONSTRAINT "Submission_formId_fkey" FOREIGN KEY ("formId") REFERENCES "Form"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Submission" ADD CONSTRAINT "Submission_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "ApplicationCampaign"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Submission" ADD CONSTRAINT "Submission_personId_fkey" FOREIGN KEY ("personId") REFERENCES "Person"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Submission" ADD CONSTRAINT "Submission_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Application" ADD CONSTRAINT "Application_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "ApplicationCampaign"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Application" ADD CONSTRAINT "Application_personId_fkey" FOREIGN KEY ("personId") REFERENCES "Person"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Application" ADD CONSTRAINT "Application_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Application" ADD CONSTRAINT "Application_entrepreneurId_fkey" FOREIGN KEY ("entrepreneurId") REFERENCES "Entrepreneur"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Reservation" ADD CONSTRAINT "Reservation_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Reservation" ADD CONSTRAINT "Reservation_personId_fkey" FOREIGN KEY ("personId") REFERENCES "Person"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Reservation" ADD CONSTRAINT "Reservation_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OperationalReport" ADD CONSTRAINT "OperationalReport_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EntrepreneurProgram" ADD CONSTRAINT "EntrepreneurProgram_entrepreneurId_fkey" FOREIGN KEY ("entrepreneurId") REFERENCES "Entrepreneur"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EntrepreneurProgram" ADD CONSTRAINT "EntrepreneurProgram_programId_fkey" FOREIGN KEY ("programId") REFERENCES "Program"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "KvkkConsent" ADD CONSTRAINT "KvkkConsent_personId_fkey" FOREIGN KEY ("personId") REFERENCES "Person"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FundingSource" ADD CONSTRAINT "FundingSource_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FundingReceipt" ADD CONSTRAINT "FundingReceipt_fundingSourceId_fkey" FOREIGN KEY ("fundingSourceId") REFERENCES "FundingSource"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ProjectExpense" ADD CONSTRAINT "ProjectExpense_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RentContract" ADD CONSTRAINT "RentContract_entrepreneurId_fkey" FOREIGN KEY ("entrepreneurId") REFERENCES "Entrepreneur"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RentAccrual" ADD CONSTRAINT "RentAccrual_contractId_fkey" FOREIGN KEY ("contractId") REFERENCES "RentContract"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RentAccrual" ADD CONSTRAINT "RentAccrual_entrepreneurId_fkey" FOREIGN KEY ("entrepreneurId") REFERENCES "Entrepreneur"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RentPayment" ADD CONSTRAINT "RentPayment_accrualId_fkey" FOREIGN KEY ("accrualId") REFERENCES "RentAccrual"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RentPayment" ADD CONSTRAINT "RentPayment_entrepreneurId_fkey" FOREIGN KEY ("entrepreneurId") REFERENCES "Entrepreneur"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ApplicationCampaign" ADD CONSTRAINT "ApplicationCampaign_programId_fkey" FOREIGN KEY ("programId") REFERENCES "Program"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ApplicationCampaign" ADD CONSTRAINT "ApplicationCampaign_formId_fkey" FOREIGN KEY ("formId") REFERENCES "Form"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ApplicationCampaign" ADD CONSTRAINT "ApplicationCampaign_evaluationTemplateId_fkey" FOREIGN KEY ("evaluationTemplateId") REFERENCES "EvaluationTemplate"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ApplicationCampaign" ADD CONSTRAINT "ApplicationCampaign_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SpaceAssignment" ADD CONSTRAINT "SpaceAssignment_facilityId_fkey" FOREIGN KEY ("facilityId") REFERENCES "Facility"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SpaceAssignment" ADD CONSTRAINT "SpaceAssignment_entrepreneurId_fkey" FOREIGN KEY ("entrepreneurId") REFERENCES "Entrepreneur"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SpaceAssignment" ADD CONSTRAINT "SpaceAssignment_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SpaceAssignment" ADD CONSTRAINT "SpaceAssignment_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SpaceAssignment" ADD CONSTRAINT "SpaceAssignment_rentContractId_fkey" FOREIGN KEY ("rentContractId") REFERENCES "RentContract"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FacilityExperience" ADD CONSTRAINT "FacilityExperience_facilityId_fkey" FOREIGN KEY ("facilityId") REFERENCES "Facility"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FacilityHotspot" ADD CONSTRAINT "FacilityHotspot_experienceId_fkey" FOREIGN KEY ("experienceId") REFERENCES "FacilityExperience"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Document" ADD CONSTRAINT "Document_mediaId_fkey" FOREIGN KEY ("mediaId") REFERENCES "Media"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NotificationRead" ADD CONSTRAINT "NotificationRead_notificationId_fkey" FOREIGN KEY ("notificationId") REFERENCES "Notification"("id") ON DELETE CASCADE ON UPDATE CASCADE;

